# version: '3.9'

# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=db
#     container_name: postgres
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data
#     ports:
#       - '5432:5432'

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: nest-docker-postgres
#     environment:
#        - POSTGRES_HOST=postgres
#        - POSTGRES_PASSWORD=postgres
#        - POSTGRES_USER=postgres
#        - POSTGRES_DB=db
#        - POSTGRES_PORT=5432
#     ports:
#       - '3000:3000'
#     depends_on:
#       - db
#     volumes:
#       - ./src:/app/src

#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     container_name: nest-pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#       - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#     ports:
#       - '5050:80'
#     depends_on:
#       - db
version: '3.8'

services :
  db:
   image: postgres
   restart: always
   ports:
     - "5432:5432"
   environment:
    POSTGRES_PASSWORD: postgres
